### PR TITLE
Fix make clean for vst3

### PR DESCRIPTION
**Pull request by noisecode3**
I think It makes sense to clean up .vst3 the same way .lv2 gets clean up. Or maybe I missed something. By the way thanks for vst3 support and all the work on DPF.

### CODE REVIEW

**Comment by falkTX** [comment]
ah yes, you are quite correct.
can you also add `$(TARGET_DIR)/$(NAME).vst` while at it too? there is a flag now to turn the vst single file into a bundle, so we can put resource files into it.
thanks!

**Comment by noisecode3** [comment]
Its added :)

**Comment by lucianoiam** [comment]
I was about to open an identical PR, so +1 to this

**Comment by falkTX** [comment]
Handled in e2dcae3758684b8c6a3157da71aad3757c9e652c
Thanks

**Pull request closed without merging**
