### PR TITLE
Feature/windows xpile 2

### PR DESCRIPTION
**Pull request by guysherman**
- Added ability to display an error message when trying to open lv2 dlls on Windows (in lv2_ttl_generator).
- Added a windows batch file analogous to generate-ttl.sh

### CODE REVIEW

**Comment by falkTX** [comment]
Can you tell me why this is needed?
Are you building the plugins with MSVC?

(also, your lv2_ttl_generator.c changes are missing an #ifdef)

**Comment by guysherman** [comment]
I'll fix the .c file - bad copy paste :(

I have been working on cross compiling from the Windows Subsytem for Linux (essentially Ubuntu 14.04, but running on Windows). 

The one problem was that you can't run the lvw_ttl_generator.exe from the bash console (because unlike msys2, it is actually a linux environment), so you have to run it from the windows command-prompt after you finish compiling (I can submit a PR to your sample repository as well, to fold in the changes from the 'consumer' side). I wrote a batch file to do the same job as the shell script. 

The changes to lv2_ttl_generator are helpful for tracking down dll hell.

**Comment by falkTX** [comment]
Adding that code for windows will require linking to windows libraries.
I'll have to make it optional.

**Comment by guysherman** [comment]
I didn't have to add any link flags.

**Comment by falkTX** [comment]
afaik the ubuntu-for-windows thing can now run windows binaries, so this PR might not be needed anymore.

**Comment by falkTX** [comment]
I am closing this issue due to not being needed anymore, and not something I am supporting right now.
Thanks anyway.

**Pull request closed without merging**
