### PR TITLE
Fix swapped minor/micro version number when exporting LV2 TTL

### PR DESCRIPTION
**Pull request by SpotlightKid**
Reference: http://lv2plug.in/ns/lv2core/lv2core.html#minorVersion

See also `d_version` in [DistrhoUtils.hpp](distrho/DistrhoUtils.hpp#69).

### CODE REVIEW

**Comment by SpotlightKid** [comment]
I'm also not sure about what the `if (majorVersion > 0) minorVersion += 2;` is supposed to solve. But that would be for another PR, I guess.

**Comment by jpcima** [comment]
At first look, I think this fix to make sense, it will be nice to have it.

>I'm also not sure about what the if (majorVersion > 0) minorVersion += 2; is supposed to solve. But that would be for another PR, I guess.

From what I learnt recently on LV2 versioning, a version is considered prerelease under either these conditions:
1. either minor or micro is odd
2. micro is 0

As I understand, this check is to prevent the case 2. to happen.
By DPF's definition, major=0 is intended for prerelease, major>0 for final.

**Comment by SpotlightKid** [comment]
> micro is 0

Actually, "minor == 0":

> An odd minor or micro version, or minor version zero, indicates that the resource is a development version.

http://lv2plug.in/ns/lv2core#minorVersion

> As I understand, this check is to prevent the case 2. to happen.

But why? Why can't one have pre-releases when the major version is >= 1?

**Comment by falkTX** [comment]
is that a dpf question or lv2 question?

**Comment by SpotlightKid** [comment]
A DPF question. In LV2, the major version is the plugin URI, so the major version set with d_version is irrelevant. I don't see anything in the LV2 spec forbidding an odd minor ot micro version, i.e. a pre-release, even after a previous release had even verdion numbers.

**Comment by falkTX** [comment]
To come back to this, my point was to prevent 1.0.0 to turn up as 0.0 and thus be marked as experimental/unstable on lv2 side.

**Comment by falkTX** [comment]
Changes have been pushed to develop branch a while ago, forgot to close this PR, doing that now.

**Pull request closed without merging**
