### PR TITLE
Add loongarch64 support

### PR DESCRIPTION
**Pull request by YHStar**
[LoongArch](https://docs.kernel.org/arch/loongarch/introduction.html) is a new RISC ISA developed by Loongson. There are already a lot of [community support and testing](https://www.phoronix.com/search/LoongArch) about it.

Hello, I'm working on porting ArchLinux to Loongarch64. Would you please review my changes and support Loongarch64? It's tested on LoongArchLinux.Thank you.

### CODE REVIEW

**Comment by falkTX** [comment]
is this the string selected from steinberg for the vst3 spec?
According to https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Locations+Format/Plugin+Format.html#for-the-linux-platform

> with XXX the architecture name based on the output of command-line "uname -m" (machine hardware) + "-linux"

so what does `uname -m` return on a Loongarch64 system?

**Comment by falkTX** [comment]
seems good to me, but I need to ask to target develop branch instead of main.

**Comment by YHStar** [comment]
Adjusted

**Comment by falkTX** [comment]
This was fixed in cc35a95d5994fbc1fed756d229ced10bf075f509 in a more generic way

**Pull request closed without merging**
