### PR TITLE
CLAP: add macro to use MIDI MPE dialect

### PR DESCRIPTION
**Pull request by jfrey-xx**
This is related to #441 

In the end I could not help but try a little something. At first I wanted to let people select any of the different dialects, but I was not sure how to properly retrieve the definitions in DPF (include the corresponding CLAP header or duplicate its `#define` somewhere? Neither seemed pretty). So I settled with just the "MPE" option for now, especially considering that the other dialects (MDI 2 or CLAP) might need to be properly parsed to reach the plugin.

Then I started to add flags to let user configure MPE for input or output separately, to declare it as supported only (and not "preferred")... but that started to look bloated without other use cases.

Hence the trivial modification. I still hope that can be of some help. I tried my best to mimic how the flags are set. Tell me if I can improve something.

### CODE REVIEW

**Comment by falkTX** [comment]
While I agree with the base idea, I think making this clap specific is wrong.
Best to me seems to have a generic hint (0/off by default if unset) to report a plugin as supporting MPE. Then DPF takes care that the host knows about this, which is already covered here for CLAP.
The value is only a hint anyway, so it is fine to be generic.

**Comment by falkTX** [comment]
While I agree with the base idea, I think making this clap specific is wrong.
Best to me seems to have a generic hint (0/off by default if unset) to report a plugin as supporting MPE. Then DPF takes care that the host knows about this, which is already covered here for CLAP.
The value is only a hint anyway, so it is fine to be generic.

**Comment by falkTX** [comment]
also please make the PR target develop branch, not main.
new commits should always go into develop first. thanks

**Comment by falkTX** [comment]
actually I think the best is to have default value as "undefined", where we do nothing special if unset.
but plugins can manually specify through 0 or 1 value that they support MPE (or not)

most plugin specs dont have a way to report this property anyhow

**Comment by jfrey-xx** [comment]
Thanks for the feedback. I rebased on develop and used a generic name for the macro -- maybe there is a better name for that (`DISTRHO_PLUGIN_USE_MIDI_MPE ` ?), maybe you wanted no default value in `DistrhoInfo.hpp`.

**Comment by falkTX** [comment]
sorry it took a while to get to this, I want to add a few little things on top but never had the time for it, so best to merge it as-is.
I just now need to handle it similar to the other flags

thanks!

**Comment by jfrey-xx** [comment]
No worries, thank you for getting back to that :) Now I definitely have to polish and publish the plugins I have been working on!

**Comment by falkTX** [comment]
> No worries, thank you for getting back to that :) Now I definitely have to polish and publish the plugins I have been working on!

yes! then please update https://github.com/DISTRHO/DPF/wiki/Plugins-made-with-DPF to mention those too

**Comment by jfrey-xx** [comment]
Sure will!

**Pull request merged**
