### PR TITLE
Add Shiro-plugins

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by falkTX** [comment]
This is nice, but it is all quite unsorted...
If we keep adding more, would be nice if names are sorted alphabetically

**Comment by trebmuh** [comment]
Would you mind merging this one, and I'll sort them afterwards in another PR ?

**Comment by falkTX** [comment]
That is quite fair, will merge then

**Comment by trebmuh** [comment]
ty

**Pull request merged**
