### PR TITLE
CMake: Add SDL2 dependency libraries on Win32 JACK build

### PR DESCRIPTION
**Pull request by AnClark**
SDL2 depends on some native Win32 system libraries when building on Windows.

<details><summary>Linker error log on Windows 10 with Msys2</summary>

```log
[28/28] Linking CXX executable bin\casynth_dpf.exe
FAILED: bin/casynth_dpf.exe
cmd.exe /C "cd . && C:\msys64\mingw64\bin\c++.exe -Wall -g -O3 -DNDEBUG  plugins/casynth/CMakeFiles/casynth_dpf-jack.dir/__/__/vendor/dpf/distrho/DistrhoPluginMain.cpp.obj plugins/casynth/CMakeFiles/casynth_dpf-jack.dir/__/__/vendor/dpf/distrho/DistrhoUIMain.cpp.obj -o bin\casynth_dpf.exe -Wl,--out-implib,plugins\casynth\libcasynth_dpf.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -LD:/Sources/infamousPlugins/build/usr/lib -static  plugins/casynth/libcasynth_dpf-dsp.a  plugins/casynth/libcasynth_dpf-ui.a  -lmingw32  -lSDL2main  -lSDL2  -ldsound  -lole32  -lwinmm  plugins/casynth/libcasynth_dpf.a  vendor/fltk/lib/libfltk.a  C:/msys64/usr/lib/libdl.a  -lcomctl32  -lws2_32  vendor/fltk/lib/libfltk_cairo.a  vendor/fltk/lib/libfltk_z.a  -lcairo  -lpixman-1  -lfontconfig  -lfreetype  -lintl  -liconv  -lbz2  -lbrotlidec  -lbrotlicommon  -lharfbuzz  -lgraphite2  -lpng16  -lz  -lexpat  -lMsimg32 
 -lRpcrt4  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_hidapi.c.obj):(.text+0x11bf): undefined reference to `__imp_SetupDiGetClassDevsA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_hidapi.c.obj):(.text+0x11c6): undefined reference to `__imp_SetupDiEnumDeviceInterfaces'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_hidapi.c.obj):(.text+0x11d6): undefined reference to `__imp_SetupDiGetDeviceInterfaceDetailA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_hidapi.c.obj):(.text+0x129f): undefined reference to `__imp_SetupDiEnumDeviceInfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_hidapi.c.obj):(.text+0x12ae): undefined reference to `__imp_SetupDiGetDeviceRegistryPropertyA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_hidapi.c.obj):(.text+0x1465): undefined reference to `__imp_SetupDiDestroyDeviceInfoList'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0xae): undefined reference to `ImmGetIMEFileNameA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x103): undefined reference to `ImmGetContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x129): undefined reference to `ImmReleaseContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x167): undefined reference to `ImmGetCompositionStringW'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x18b): undefined reference to `ImmGetCompositionStringW'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x1ad): undefined reference to `ImmGetCompositionStringW'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x2cf): undefined reference to `ImmGetCompositionStringW'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x30e): undefined reference to `ImmGetCompositionStringW'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x57d): undefined reference to `ImmGetIMEFileNameA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x6c9): undefined reference to `GetFileVersionInfoSizeA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x6f5): undefined reference to `GetFileVersionInfoA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x756): undefined reference to `VerQueryValueA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x931): undefined reference to `ImmGetContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x953): undefined reference to `ImmNotifyIME'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x970): undefined reference to `ImmNotifyIME'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x97f): undefined reference to `ImmReleaseContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x9c3): undefined reference to `ImmSetCompositionStringW'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0xaab): undefined reference to `ImmAssociateContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0xe7e): undefined reference to `ImmGetContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0xe90): undefined reference to `ImmReleaseContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x1a03): undefined reference to `ImmAssociateContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x1d38): undefined reference to `ImmAssociateContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x1e8b): undefined reference to `ImmGetContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x1ed8): undefined reference to `ImmSetCompositionWindow'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x1f1d): undefined reference to `ImmSetCandidateWindow'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x1f2c): undefined reference to `ImmReleaseContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x2060): undefined reference to `ImmGetContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x20ae): undefined reference to `ImmReleaseContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x22c1): undefined reference to `ImmGetContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x22dd): undefined reference to `ImmGetCandidateListW'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x22f3): undefined reference to `ImmReleaseContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x2351): undefined reference to `ImmGetContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x23f2): undefined reference to `ImmReleaseContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x2702): undefined reference to `ImmGetCandidateListW'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x33a8): undefined reference to `ImmGetContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x33c6): undefined reference to `ImmNotifyIME'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x33e3): undefined reference to `ImmNotifyIME'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x33f2): undefined reference to `ImmReleaseContext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windowskeyboard.c.obj):(.text+0x3433): undefined reference to `ImmSetCompositionStringW'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windows_gaming_input.c.obj):(.text+0x10cf): undefined reference to `__imp_CM_Locate_DevNodeA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windows_gaming_input.c.obj):(.text+0x1120): undefined reference to `__imp_CM_Get_Parent'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libSDL2.a(SDL_windows_gaming_input.c.obj):(.text+0x1141): undefined reference to `__imp_CM_Get_Device_IDA'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

```

</details>

### CODE REVIEW

**Comment by falkTX** [comment]
That block needs to be `if (WIN32 AND SDL2_FOUND)`.
But how come these libs are not part of `${SDL2_LIBRARIES}` ?

**Comment by falkTX** [comment]
Actually, best to put it right after `dpf__target_link_directories("${NAME}-jack" ${SDL2_LIBRARY_DIRS})` on a `if(WIN32)` block

**Comment by AnClark** [comment]
> That block needs to be if (WIN32 AND SDL2_FOUND).
> But how come these libs are not part of ${SDL2_LIBRARIES} ?

That's so strange.

But it appears that `pkg-config` populates SDL2 libraries in shared mode, so it is lack of those Win32 libs.

Here are `pkg-config` outputs in my Msys2 MinGW-w64-x86_64 environment:

```bash
$ pkg-config --libs --static sdl2
-LC:/msys64/mingw64/bin/../lib -lmingw32 -mwindows -lSDL2main -lSDL2 -lmingw32 -mwindows -lSDL2main -lSDL2 -lm -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion -luuid -ladvapi32 -lsetupapi -lshell32 -ldinput8
``` 

```bash
$ pkg-config --libs sdl2
-LC:/msys64/mingw64/bin/../lib -lmingw32 -mwindows -lSDL2main -lSDL2
```

**Comment by AnClark** [comment]
I've rebased this branch with my new modifications. Here I replaced `pkg-config`-related variables from `${SDL2_xxxxxx}` to`${SDL2_STATIC_xxxxxx}`. This prefers static libraries.

**Comment by falkTX** [comment]
Looks good to me, will merge!

**Comment by AnClark** [comment]
Thanks!

**Comment by AnClark** [comment]
BTW, I forgot to modify my commit message to explain why I'm using those variables. Will it make a confuse?

This is the original commit message:
```
CMake: Add SDL2 dependency libs on Win32 JACK build

SDL2 depends on some native Win32 system libraries when building on
Windows.
```

**Comment by falkTX** [comment]
it is fine, commit is kinda clear

**Comment by AnClark** [comment]
OK, thanks.

**Pull request merged**
