### PR TITLE
Vst key events

### PR DESCRIPTION
**Pull request by fundamental**
- Fixes Ctrl/Shift/Alt event handling
- Fixes build for Zyn's ntk external UI

See also: https://github.com/DISTRHO/DPF/issues/19

For zyn-fusion I've internally implemented a fix for the repeated key presses. With these changes I'd say the vst-key-event handling should be good enough to merge into master, though that's your call in the end.

If nothing else merging these with the DISTRHO/DPF repo should make it easy for me to get out some more builds with the fixes with the build-from-scratch scripts I have.

### CODE REVIEW

**Comment by fundamental** [comment]
@falkTX would you mind reposting your question? I don't see it in this PR or in any of the commits associated with this PR.

**Comment by falkTX** [comment]
In line 216, `if (index > 0 || (value == 7 && index == 0))`
> index is 0 here, which means no key pressed right?
> what is the reason for this change?

**Comment by fundamental** [comment]
When pressing space in reaper I see index=0, value=7. All other keys that I have looked at the debug output seem to indicate that index=0 generally means special (non-numeric/alphabetic/basic symbol key).

**Comment by falkTX** [comment]
I understand that, but right now the code will be calling handlePluginKeyboard() with a key id 0 (index variable is the one passed to that function).
I suggest addline a line right after https://github.com/fundamental/DPF/blob/32239a031399cbb900f69e9c561635887416734d/distrho/src/DistrhoPluginVST.cpp#L186
like this:
```
case 7: index = ' '; break;
```
what do you think?

**Comment by fundamental** [comment]
Sounds fine to me and it appears to work in my testing setup. The fix has been added to this PR.

**Comment by falkTX** [comment]
I imported the commit that was clean, and did the rest myself (wanted to reword some comments there).
I also added a print for the host name when the UI is started, and put the code in place to start the white-list.
This is only needed on windows right? or is macOS affected too?
We should run the plugin in the affected hosts, listen to the printed messages and add to the whitelist.
The host-name print will remain to make it easier to add new names to the list later.

**Pull request closed without merging**
