### PR TITLE
lv2: Fix bug with multiple output param ports generating invalid ttl

### PR DESCRIPTION
**Pull request by zamaudio**

### CODE REVIEW

**Comment by falkTX** [comment]
I appreciate the PR, but the reason output ports are at the end is for VST.. so if you want this you'll have to patch VST state save too.
This will break compatibility between old and new plugin versions though.

**Comment by zamaudio** [comment]
Just to clarify, are the output ports supposed to be all at the top?

**Comment by falkTX** [comment]
On the contrary, output ports should be at the very end.

**Comment by zamaudio** [comment]
In that case, there is a bug with master DPF because it currently generates invalid preset turtle, even when all the output ports are at the very end.

**Comment by zamaudio** [comment]
See lv2info urn:zamaudio:ZaMaximX2 as an example.

**Comment by falkTX** [comment]
I am finishing the last Carla stuff at the moment, I will take a look at DPF stuff very soon

**Comment by zamaudio** [comment]
This PR actually fixes the problem I am suggesting but as an additional thing it allows the ports to be in any order to still generate valid preset turtle.

**Comment by zamaudio** [comment]
Sure, whenever you get a chance thanks.

**Comment by zamaudio** [comment]
New force pushed PR ^^ fixes the problem I was facing.  Basically when there are multiple output param ports, the code that generates the presets.ttl can't tell when there is more than one output port below the next one.

**Comment by zamaudio** [comment]
Without the above patch, I get:
```
error: /usr/local/lib/lv2/ZamComp.lv2/presets.ttl:38:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZamComp.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZamComp.lv2/presets.ttl:38:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZamComp.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZamComp.lv2/presets.ttl:38:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZamComp.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZamCompX2.lv2/presets.ttl:42:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZamCompX2.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZamCompX2.lv2/presets.ttl:42:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZamCompX2.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZamCompX2.lv2/presets.ttl:42:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZamCompX2.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZaMultiComp.lv2/presets.ttl:118:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZaMultiComp.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZaMultiComp.lv2/presets.ttl:118:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZaMultiComp.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZaMultiCompX2.lv2/presets.ttl:118:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZaMultiCompX2.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZaMultiCompX2.lv2/presets.ttl:118:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZaMultiCompX2.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZamGate.lv2/presets.ttl:30:0: expected object
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZamGate.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZamGateX2.lv2/presets.ttl:30:0: expected object
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZamGateX2.lv2/presets.ttl'
error: /usr/local/lib/lv2/ZaMaximX2.lv2/presets.ttl:18:0: expected object
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/ZaMaximX2.lv2/presets.ttl'
```
But with the patch above, all the errors go away.

**Comment by falkTX** [comment]
thanks!

though there must be a reason I had that j+2 code there before..
do me a favor and enable latency in one of your plugins that uses outputs.
(the latency macro as 1 is enough, then rebuild)

if this passes the ttl generation and the ttl is also valid, I'll merge the PR.

**Comment by zamaudio** [comment]
```
@prefix doap: <http://usefulinc.com/ns/doap#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix lv2:  <http://lv2plug.in/ns/lv2core#> .
@prefix mod:  <http://moddevices.com/ns/mod#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rsz:  <http://lv2plug.in/ns/ext/resize-port#> .
@prefix ui:   <http://lv2plug.in/ns/extensions/ui#> .
@prefix unit: <http://lv2plug.in/ns/extensions/units#> .

<urn:zamaudio:ZaMultiCompX2>
    a lv2:Plugin ;

    lv2:extensionData <http://lv2plug.in/ns/ext/state#interface> ,
                      <http://kxstudio.sf.net/ns/lv2ext/programs#Interface> ;

    lv2:optionalFeature <http://lv2plug.in/ns/lv2core#hardRTCapable> ,
                        <http://lv2plug.in/ns/ext/buf-size#boundedBlockLength> ;

    lv2:requiredFeature <http://lv2plug.in/ns/ext/options#options> ,
                        <http://lv2plug.in/ns/ext/urid#map> ;

    ui:ui <urn:zamaudio:ZaMultiCompX2#UI> ;

    lv2:port [
        a lv2:InputPort, lv2:AudioPort ;
        lv2:index 0 ;
        lv2:symbol "lv2_audio_in_1" ;
        lv2:name "Audio Input 1" ;
    ] ,
    [
        a lv2:InputPort, lv2:AudioPort ;
        lv2:index 1 ;
        lv2:symbol "lv2_audio_in_2" ;
        lv2:name "Audio Input 2" ;
    ] ;

    lv2:port [
        a lv2:OutputPort, lv2:AudioPort ;
        lv2:index 2 ;
        lv2:symbol "lv2_audio_out_1" ;
        lv2:name "Audio Output 1" ;
    ] ,
    [
        a lv2:OutputPort, lv2:AudioPort ;
        lv2:index 3 ;
        lv2:symbol "lv2_audio_out_2" ;
        lv2:name "Audio Output 2" ;
    ] ;

    lv2:port [
        a lv2:OutputPort, lv2:ControlPort ;
        lv2:index 4 ;
        lv2:name "Latency" ;
        lv2:symbol "lv2_latency" ;
        lv2:designation lv2:latency ;
        lv2:portProperty lv2:reportsLatency, lv2:integer, <http://lv2plug.in/ns/ext/port-props#notOnGUI> ;
    ] ;

    lv2:port [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 5 ;
        lv2:name "Attack1" ;
        lv2:symbol "att1" ;
        lv2:default 10.000000 ;
        lv2:minimum 0.100000 ;
        lv2:maximum 100.000000 ;
        unit:unit unit:ms ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 6 ;
        lv2:name "Attack2" ;
        lv2:symbol "att2" ;
        lv2:default 10.000000 ;
        lv2:minimum 0.100000 ;
        lv2:maximum 100.000000 ;
        unit:unit unit:ms ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 7 ;
        lv2:name "Attack3" ;
        lv2:symbol "att3" ;
        lv2:default 10.000000 ;
        lv2:minimum 0.100000 ;
        lv2:maximum 100.000000 ;
        unit:unit unit:ms ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 8 ;
        lv2:name "Release1" ;
        lv2:symbol "rel1" ;
        lv2:default 80.000000 ;
        lv2:minimum 1.000000 ;
        lv2:maximum 500.000000 ;
        unit:unit unit:ms ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 9 ;
        lv2:name "Release2" ;
        lv2:symbol "rel2" ;
        lv2:default 80.000000 ;
        lv2:minimum 1.000000 ;
        lv2:maximum 500.000000 ;
        unit:unit unit:ms ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 10 ;
        lv2:name "Release3" ;
        lv2:symbol "rel3" ;
        lv2:default 80.000000 ;
        lv2:minimum 1.000000 ;
        lv2:maximum 500.000000 ;
        unit:unit unit:ms ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 11 ;
        lv2:name "Knee1" ;
        lv2:symbol "kn1" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 8.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 12 ;
        lv2:name "Knee2" ;
        lv2:symbol "kn2" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 8.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 13 ;
        lv2:name "Knee3" ;
        lv2:symbol "kn3" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 8.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 14 ;
        lv2:name "Ratio1" ;
        lv2:symbol "rat1" ;
        lv2:default 4.000000 ;
        lv2:minimum 1.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty <http://lv2plug.in/ns/ext/port-props#logarithmic> ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 15 ;
        lv2:name "Ratio2" ;
        lv2:symbol "rat2" ;
        lv2:default 4.000000 ;
        lv2:minimum 1.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty <http://lv2plug.in/ns/ext/port-props#logarithmic> ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 16 ;
        lv2:name "Ratio3" ;
        lv2:symbol "rat3" ;
        lv2:default 4.000000 ;
        lv2:minimum 1.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty <http://lv2plug.in/ns/ext/port-props#logarithmic> ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 17 ;
        lv2:name "Threshold 1" ;
        lv2:symbol "thr1" ;
        lv2:default -20.000000 ;
        lv2:minimum -60.000000 ;
        lv2:maximum 0.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 18 ;
        lv2:name "Threshold 2" ;
        lv2:symbol "thr2" ;
        lv2:default -18.000000 ;
        lv2:minimum -60.000000 ;
        lv2:maximum 0.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 19 ;
        lv2:name "Threshold 3" ;
        lv2:symbol "thr3" ;
        lv2:default -16.000000 ;
        lv2:minimum -60.000000 ;
        lv2:maximum 0.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 20 ;
        lv2:name "Makeup 1" ;
        lv2:symbol "mak1" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 30.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 21 ;
        lv2:name "Makeup 2" ;
        lv2:symbol "mak2" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 30.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 22 ;
        lv2:name "Makeup 3" ;
        lv2:symbol "mak3" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 30.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 23 ;
        lv2:name "Crossover freq 1" ;
        lv2:symbol "xover1" ;
        lv2:default 160.000000 ;
        lv2:minimum 20.000000 ;
        lv2:maximum 1400.000000 ;
        unit:unit unit:hz ;
        lv2:portProperty <http://lv2plug.in/ns/ext/port-props#logarithmic> ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 24 ;
        lv2:name "Crossover freq 2" ;
        lv2:symbol "xover2" ;
        lv2:default 1400.000000 ;
        lv2:minimum 1400.000000 ;
        lv2:maximum 14000.000000 ;
        unit:unit unit:hz ;
        lv2:portProperty <http://lv2plug.in/ns/ext/port-props#logarithmic> ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 25 ;
        lv2:name "ZamComp 1 ON" ;
        lv2:symbol "toggle1" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 1.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty lv2:toggled ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 26 ;
        lv2:name "ZamComp 2 ON" ;
        lv2:symbol "toggle2" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 1.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty lv2:toggled ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 27 ;
        lv2:name "ZamComp 3 ON" ;
        lv2:symbol "toggle3" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 1.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty lv2:toggled ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 28 ;
        lv2:name "Listen 1" ;
        lv2:symbol "listen1" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 1.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty lv2:toggled ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 29 ;
        lv2:name "Listen 2" ;
        lv2:symbol "listen2" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 1.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty lv2:toggled ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 30 ;
        lv2:name "Listen 3" ;
        lv2:symbol "listen3" ;
        lv2:default 0.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 1.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty lv2:toggled ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 31 ;
        lv2:name "Detection (MAX/avg)" ;
        lv2:symbol "stereodet" ;
        lv2:default 1.000000 ;
        lv2:minimum 0.000000 ;
        lv2:maximum 1.000000 ;
        unit:unit [
            rdfs:label  " " ;
            unit:symbol " " ;
            unit:render "%f  " ;
        ] ;
        lv2:portProperty lv2:toggled ;
    ] ,
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 32 ;
        lv2:name "Master Trim" ;
        lv2:symbol "globalgain" ;
        lv2:default 0.000000 ;
        lv2:minimum -12.000000 ;
        lv2:maximum 12.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:OutputPort, lv2:ControlPort ;
        lv2:index 33 ;
        lv2:name "Output Left" ;
        lv2:symbol "outl" ;
        lv2:minimum -45.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:OutputPort, lv2:ControlPort ;
        lv2:index 34 ;
        lv2:name "Output Right" ;
        lv2:symbol "outr" ;
        lv2:minimum -45.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:OutputPort, lv2:ControlPort ;
        lv2:index 35 ;
        lv2:name "Output low" ;
        lv2:symbol "outlo" ;
        lv2:minimum -45.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:OutputPort, lv2:ControlPort ;
        lv2:index 36 ;
        lv2:name "Output medium" ;
        lv2:symbol "outmed" ;
        lv2:minimum -45.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:OutputPort, lv2:ControlPort ;
        lv2:index 37 ;
        lv2:name "Output high" ;
        lv2:symbol "outhi" ;
        lv2:minimum -45.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:OutputPort, lv2:ControlPort ;
        lv2:index 38 ;
        lv2:name "Gain Reduction 1" ;
        lv2:symbol "gr1" ;
        lv2:minimum 0.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:OutputPort, lv2:ControlPort ;
        lv2:index 39 ;
        lv2:name "Gain Reduction 2" ;
        lv2:symbol "gr2" ;
        lv2:minimum 0.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit unit:db ;
    ] ,
    [
        a lv2:OutputPort, lv2:ControlPort ;
        lv2:index 40 ;
        lv2:name "Gain Reduction 3" ;
        lv2:symbol "gr3" ;
        lv2:minimum 0.000000 ;
        lv2:maximum 20.000000 ;
        unit:unit unit:db ;
    ] ;

    rdfs:comment """
Flagship of zam-plugins:
Stereo version of ZaMultiComp, with individual threshold controls for each band and real-time visualisation of comp curves.
""" ;

    mod:brand "ZamAudio" ;
    mod:label "ZaMultiCompX2" ;

    doap:name "ZaMultiCompX2" ;
    doap:license "GPL v2+" ;

    doap:maintainer [
        foaf:name "Damien Zammit" ;
        foaf:homepage <http://www.zamaudio.com> ;
    ] ;

    lv2:microVersion 9 ;
    lv2:minorVersion 2 .

```
This is the generated .ttl for one of my plugins using latency macro enabled and it still builds all valid .ttl for everything.

**Comment by falkTX** [comment]
Alright, looks good.
Thank you.

**Pull request merged**
