### PR TITLE
Export LV2 scalePoint for integer ports as integer values not float

### PR DESCRIPTION
**Pull request by SpotlightKid**
Signed-off-by: Christopher Arndt <chris@chrisarndt.de>

### CODE REVIEW

**Comment by falkTX** [comment]
This is helpful, thanks.
But I think the value should be rounded. If the value is 2.999, for example, flushing it to 2 doesn't seem right.
We can easily do this by adding 0.5 to the value `int var = (int)(floatvar + 0.5f);` which will truncate/flush-down the value in a rounding way.

**Comment by SpotlightKid** [comment]
Ok, I've pushed a commit that does as you suggest.

**Comment by falkTX** [comment]
Thanks!
I hate to be picky (hmm or maybe not :P) but such variables should be marked `const` :)

**Comment by SpotlightKid** [comment]
Ok, btw, which naming style for local variables? All lowercase, no underscore ok?

**Comment by falkTX** [comment]
CamelCase for class names and variables, with classes started with an uppercase letter.

**Comment by SpotlightKid** [comment]
Feel free to squash the commits.

**Comment by falkTX** [comment]
thanks, will do

**Pull request merged**
