### PR TITLE
Fix target compiler detection

### PR DESCRIPTION
**Pull request by pdesaulniers**
Suggested fix for https://github.com/DISTRHO/DPF/issues/395

### CODE REVIEW

**Comment by falkTX** [comment]
See CI, this already fails

**Comment by falkTX** [comment]
This works here:
```sh
TARGET_COMPILER = $(shell printf '\#ifdef __clang__\nclang\n\#else\ngcc\n\#endif' | $(CC) -E -P -x c - 2>/dev/null)
```

but I guess it will fail for you..

**Comment by pdesaulniers** [comment]
Oh yes, sorry, I thought the hash sign escaping quirks were a part of `echo` :(

> but I guess it will fail for you..

Yes, that's right, it fails on my system.

Would it be reasonable to simplify the check to `ifneq (,$(findstring clang,$(CC)))` ?

**Comment by falkTX** [comment]
> Would it be reasonable to simplify the check to `ifneq (,$(findstring clang,$(CC)))` ?

no, calling "gcc" on macos will run clang
the command "gcc" is often an alias to the real compiler.

**Comment by falkTX** [comment]
the fix involves this exact check:
```
ifeq ($(shell echo '\#test' | grep -- '\#test'),\#test)
```
this is what detects if the makefile needs special escaping or not.

**Comment by pdesaulniers** [comment]
The issue has been fixed by https://github.com/DISTRHO/DPF/commit/c7e4ac43f5228cee69b2453d95e56859d7912a50 and https://github.com/DISTRHO/DPF/commit/34952157be7db5e01c58266431aab253b59f9259, so I am closing this PR.

**Pull request closed without merging**
