### PR TITLE
Clamp log knob values

### PR DESCRIPTION
**Pull request by zamaudio**
Signed-off-by: Damien Zammit <damien@zamaudio.com>

### CODE REVIEW

**Comment by zamaudio** [comment]
My last PR introduced this bug, so here's a fix.  Alternatively you can revert my last PR since I created a new widget with the needed changes instead.

**Comment by falkTX** [comment]
I agree with the change, but not how it was changed.
Use std::min(maxcalc, realmax) instead of comparing and setting maxcalc value.

**Comment by zamaudio** [comment]
Updated PR

**Comment by falkTX** [comment]
hmm wait, so the issue here is that 'value' variable is out of bounds?
seems to me that the bug is somewhere else.

**Comment by falkTX** [comment]
I think a better solution here is just comparing 'value' against minimum and maximum.
like:

```
if (value <= fMinimum)
    return value;
if (value >= fMaximum)
    return value;
// rest of the code, now safe to calculate log
```

**Comment by zamaudio** [comment]
This bug was introduced because of my last PR, can you revert it please? I don't even need it.

**Comment by falkTX** [comment]
hmm ok :)

**Pull request closed without merging**
